from DeepPurpose import utils, dataset
from DeepPurpose import DTI as models
from flask import Flask
from flask_ngrok import run_with_ngrok
#import threading

app = Flask(__name__)
run_with_ngrok(app)
@app.route("/")
def drug():
	drug_encoding, target_encoding = 'MPNN', 'AAC'
	config = utils.generate_config(drug_encoding = drug_encoding, 
				     target_encoding = target_encoding, 
				     cls_hidden_dims = [1024,1024,512], 
				     train_epoch = 5, 
				     LR = 0.001, 
				     batch_size = 128,
				     hidden_dim_drug = 128,
				     mpnn_hidden_size = 128,
				     mpnn_depth = 3, 
				     cnn_target_filters = [32,64,96],
				     cnn_target_kernels = [4,8,12]
				    )
	model = models.model_initialize(**config)

	X_drug = ['COC1=C(OCC2CCN(C)CC2)C=C2N=CN=C(NC3=C(F)C=C(Br)C=C3)C2=C1']
	X_target=['MRPSGTAGAALLALLAALCPASRALEEKKVCQGTSNKLTQLGTFEDHFLSLQRMFNNCEVVLGNLEITYVQRNYDLSFLKTIQEVAGYVLIALNTVERIPLENLQIIRGNMYYENSYALAVLSNYDANKTGLKELPMRNLQEILHGAVRFSNNPALCNVESIQWRDIVSSDFLSNMSMDFQNHLGSCQKCDPSCPNGSCWGAGEENCQKLTKIICAQQCSGRCRGKSPSDCCHNQCAAGCTGPRESDCLVCRKFRDEATCKDTCPPLMLYNPTTYQMDVNPEGKYSFGATCVKKCPRNYVVTDHGSCVRACGADSYEMEEDGVRKCKKCEGPCRKVCNGIGIGEFKDSLSINATNIKHFKNCTSISGDLHILPVAFRGDSFTHTPPLDPQELDILKTVKEITGFLLIQAWPENRTDLHAFENLEIIRGRTKQHGQFSLAVVSLNITSLGLRSLKEISDGDVIISGNKNLCYANTINWKKLFGTSGQKTKIISNRGENSCKATGQVCHALCSPEGCWGPEPRDCVSCRNVSRGRECVDKCNLLEGEPREFVENSECIQCHPECLPQAMNITCTGRGPDNCIQCAHYIDGPHCVKTCPAGVMGENNTLVWKYADAGHVCHLCHPNCTYGCTGPGLEGCPTNGPKIPSIATGMVGALLLLLVVALGIGLFMRRRHIVRKRTLRRLLQERELVEPLTPSGEAPNQALLRILKETEFKKIKVLGSGAFGTVYKGLWIPEGEKVKIPVAIKELREATSPKANKEILDEAYVMASVDNPHVCRLLGICLTSTVQLITQLMPFGCLLDYVREHKDNIGSQYLLNWCVQIAKGMNYLEDRRLVHRDLAARNVLVKTPQHVKITDFGLAKLLGAEEKEYHAEGGKVPIKWMALESILHRIYTHQSDVWSYGVTVWELMTFGSKPYDGIPASEISSILEKGERLPQPPICTIDVYMIMVKCWMIDADSRPKFRELIIEFSKMARDPQRYLVIQGDERMHLPSPTDSNFYRALMDEEDMDDVVDADEYLIPQQGFFSSPSTSRTPLLSSLSATSNNSTVACIDRNGLQSCPIKEDSFLQRYSSDPTGALTEDSIDDTFLPVPEYINQSVPKRPAGSVQNPVYHNQPLNPAPSRDPHYQDPHSTAVGNPEYLNTVQPTCVNSTFDSPAHWAQKGSHQISLDNPDYQQDFFPKEAKPNGIFKGSTAENAEYLRVAPQSSEFIGA']
	y=[0]
	X_pred = utils.data_process(X_drug, X_target, y,
				            drug_encoding, target_encoding, 
				            split_method='no_split')
	y_pred = model.predict(X_pred)
	print('The predicted score is ' + str(y_pred))

#threading.Thread(target=app.run, kwargs={'host':'0.0.0.0','port':80}).start() 
app.run()
#if __name__=="__main__":
	

